### ISSUE TITLE
Outdated install script?

### ISSUE THREAD

**Issue by ddundo** [pyroteus/pyroteus#169]
Hey @jwallwork23, I tried installing pyroteus and firedrake on the jwallwork23/parmmg-metric-based branch, using the `install_allinone.sh`script. And firedrake installs just fine. But it seems like pyadjoint isn't installed. Running burgers_ee.py (or the test_meshadapt.py test on firedrake) gives me `ModuleNotFoundError: No module named 'dolfin_adjoint_common'` (full log below). Could you please tell me if the install script is up to date?

I tried installing dolfin_adjoint, which then asked for fenics to be installed, then `ModuleNotFoundError: No module named 'FIAT.orientation_utils'`and so on...

```
Traceback (most recent call last):
  File "/home/ubuntu/software/firedrake-adapt/src/pyroteus/demos/burgers_ee.py", line 27, in <module>
    from firedrake import *
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/__init__.py", line 72, in <module>
    from firedrake.assemble import *
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/assemble.py", line 16, in <module>
    from firedrake import (extrusion_utils as eutils, matrix, parameters, solving,
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/solving.py", line 24, in <module>
    import firedrake.linear_solver as ls
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/linear_solver.py", line 2, in <module>
    import firedrake.function as function
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/function.py", line 15, in <module>
    from firedrake import functionspaceimpl
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/functionspaceimpl.py", line 18, in <module>
    from firedrake.functionspacedata import get_shared_data, create_element
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/functionspacedata.py", line 32, in <module>
    from firedrake import mesh as mesh_mod
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/mesh.py", line 31, in <module>
    from firedrake.adjoint import MeshGeometryMixin
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/__init__.py", line 1, in <module>
    from firedrake.adjoint.function import *               # noqa: F401
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/function.py", line 6, in <module>
    from firedrake.adjoint.blocks import FunctionAssignBlock, ProjectBlock, SubfunctionBlock, FunctionMergeBlock, SupermeshProjectBlock
  File "/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/blocks.py", line 1, in <module>
    from dolfin_adjoint_common.compat import compat
ModuleNotFoundError: No module named 'dolfin_adjoint_common'
```

**Comment by ddundo** [comment]
Ah thanks! I thought that the firedrake branch is "self-containing" in this sense :)
